categories:
- abschied
conversations:
- - En schöne
  - Auf wiedersehen!
- - Uf wiederluege
  - Auf wiedersehen!
- - Uf Wiedersehe
  - Auf wiedersehen!
- - Ade
  - Auf wiedersehen!
- - Ade zeme
  - Auf wiedersehen!
- - Hiube
  - Auf wiedersehen!
- - Tschüss
  - Auf wiedersehen!
- - Auf wiedersehen
  - Auf wiedersehen!
- - Bye
  - Auf wiedersehen!
- - Cya
  - Auf wiedersehen!
- - Schönen Abend
  - Auf wiedersehen!
- - Schönen Tag
  - Auf wiedersehen!
- - Schöne Woche
  - Auf wiedersehen!
- - Schönen Mittag
  - Auf wiedersehen!
