categories:
- terminanfrage
conversations:
- - Ich würde gerne einen Termin vereinbaren.
  - Testantwort Termin vereinbaren.
- - Ich brauche einen Termin für nächste Woche.
  - Testantwort nächste Woche keine Frage vereinbaren.
- - Ich möchte einen Termin haben.
  - Testantwort möchte vereinbaren.
- - Haben Sie nächste Woche Zeit für einen Termin?
  - Testantwort nächste Woche