categories:
- smalltalk
conversations:
- - Wie gehts?
  - Mir geht es gut, wie geht es Ihnen?
  - Auch gut
  - Das freut mich zu hören
- - Wie gehts dir?
  - Mir geht es gut, wie geht es Ihnen?
  - Auch gut
  - Das freut mich zu hören
- - Wie gehts Ihnen?
  - Mir geht es gut, wie geht es Ihnen?
  - Auch gut
  - Das freut mich zu hören
- - Wie gehts?
  - Mir geht es gut, wie geht es Ihnen?
  - Mir geht es auch gut
  - Das freut mich zu hören
- - Wie gehts dir?
  - Mir geht es gut, wie geht es Ihnen?
  - Mir geht es auch gut
  - Das freut mich zu hören
- - Wie gehts Ihnen?
  - Mir geht es gut, wie geht es Ihnen?
  - Mir geht es auch gut
  - Das freut mich zu hören
- - Was machst du?
  - Ich unterstütze die Praxis bei der Verarbeitung von Chat-Nachrichten über den Care Chat.
- - Was machen Sie?
  - Ich unterstütze die Praxis bei der Verarbeitung von Chat-Nachrichten über den Care Chat.