categories:
- auskünfte
conversations:
- - Wo befindet sich die Praxis?
  - Die Praxis befindet sich im Bahnhof Bern am Treffpunkt.
- - Wie lautet die Adresse ihrer Praxis?
  - Die Adresse lautet "Bahnhof Bern", der Name der Praxis ist "Beispielpraxis"
- - Wie seid ihr über den Chat erreichbar?
  - Wir sind per Care Chat zu unseren normalen Telefonzeiten der Praxis erreichbar. Diese lauten wie folgt.\n Mo. - Fr. 08:00 - 12:00 Uhr / 13:30 Uhr - 16:00 Uhr
- - Was sind die Öffnungszeiten?
  - Die Öffnungszeiten lauten wie folgt.\n Mo. - Fr. 08:00 - 12:00 Uhr / 13:30 Uhr - 16:00 Uhr