categories:
- terminanfrage
conversations:
- - Ich würde gerne einen Termin vereinbaren.
  - Leider vereinbaren wir über den Chat keine Termine, da es sonst zu Problemen mit Terminblockern kommen könnte. Bitte rufen Sie unsere Praxis an und eine Gesundheitsfachperson wird Sie dann entsprechend bei der Terminvereinbarung unterstützen.
- - Ich brauche einen Termin für nächste Woche.
  - Leider vereinbaren wir über den Chat keine Termine, da es sonst zu Problemen mit Terminblockern kommen könnte. Bitte rufen Sie unsere Praxis an und eine Gesundheitsfachperson wird Sie dann entsprechend bei der Terminvereinbarung unterstützen.
- - Ich möchte einen Termin haben.
  - Leider vereinbaren wir über den Chat keine Termine, da es sonst zu Problemen mit Terminblockern kommen könnte. Bitte rufen Sie unsere Praxis an und eine Gesundheitsfachperson wird Sie dann entsprechend bei der Terminvereinbarung unterstützen.
- - Haben Sie nächste Woche Zeit für einen Termin?
  - Leider vereinbaren wir über den Chat keine Termine, da es sonst zu Problemen mit Terminblockern kommen könnte. Bitte rufen Sie unsere Praxis an und eine Gesundheitsfachperson wird Sie dann entsprechend bei der Terminvereinbarung unterstützen.