categories:
- terminanfrage
conversations:
- - Make an appointment.
  - Man möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte eine Anpassung machen.
- - Make an appointment.
  - Ich möchte einen Termin pinkeln.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Ernennen machen.
- - Make an appointment.
  - Ich würde einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Atomic Nummer 53 möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Ernennen machen.
- - Make an appointment.
  - Atomic Nummer 53 möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Auftrag machen.
- - Make an appointment.
  - Ich möchte eine Anpassung machen.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin zusammenstellen.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte ein Engagement eingehen.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Man möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Make an appointment.
  - Ich möchte einen Termin vereinbaren.
- - Comfort no question next week.
  - Ich brauche einen Termin für die folgende Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich benötige einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für die angrenzende Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Ernennen für nächste Woche.
- - Comfort no question next week.
  - Ich brauche ein Engagement für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für die erfolgreiche Woche.
- - Comfort no question next week.
  - Ich brauche ein Engagement für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für nächste Woche.
- - Comfort no question next week.
  - Man braucht einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche eine Benennung für nächste Woche.
- - Comfort no question next week.
  - Ace braucht einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für die nächste Kalenderwoche.
- - Comfort no question next week.
  - Single braucht einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für die nächste Arbeitswoche.
- - Comfort no question next week.
  - Ich brauche einen Termin für Seite an Seite.
- - Comfort no question next week.
  - Ich brauche einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für nächste Woche.
- - Comfort no question next week.
  - Ich brauche eine Anpassung für nächste Woche.
- - Comfort no question next week.
  - Ich brauche einen Termin für Seite an Seite.
- - Comfort no question next week.
  - Ich brauche einen Termin für die nächste Arbeitswoche.
- - Comfort no question next week.
  - Ich brauche einen Termin für die folgende Woche.
- - Comfort no question next week.
  - Ich habe einen Termin für nächste Woche ein.
- - Comfort no question next week.
  - Ich brauche einen Termin für die angrenzende Woche.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte eine Bezeichnung.
- - Testet word wants to agree.
  - Single will einen Termin.
- - Testet word wants to agree.
  - Single will einen Termin.
- - Testet word wants to agree.
  - Ich wünsche einen Termin.
- - Testet word wants to agree.
  - Ich wünsche einen Termin.
- - Testet word wants to agree.
  - Ich wünsche einen Termin.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich brauche einen Termin.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte ein Date.
- - Testet word wants to agree.
  - Ich möchte einen Ernennen.
- - Testet word wants to agree.
  - Ich möchte einen Ernennen.
- - Testet word wants to agree.
  - Einheit möchte einen Termin.
- - Testet word wants to agree.
  - Ace möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte eine Aufgabe.
- - Testet word wants to agree.
  - Ich benötige einen Termin.
- - Testet word wants to agree.
  - Man möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte ein Engagement.
- - Testet word wants to agree.
  - Ich möchte eine Aufgabe.
- - Testet word wants to agree.
  - Ich möchte einen Termin.
- - Testet word wants to agree.
  - Ich möchte eine Benennung.
- - Testet word wants to agree.
  - Ich wünsche einen Termin.
- - Test word next week
  - Vereinbaren Sie, Sie haben Zeit für einen Termin nächste Woche?
- - Test word next week
  - Haben Sie Messgerät für einen Termin nächste Woche?
- - Test word next week
  - Haben Sie Messgerät für einen Termin nächste Woche?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie Zeit für eine zukünftige Terminwoche?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie nächste Woche eine Geburt für einen Termin?
- - Test word next week
  - Kommst du nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie die Uhr Zeit für einen Termin nächste Woche?
- - Test word next week
  - Vereinbaren Sie, Sie haben Zeit für einen Termin nächste Woche?
- - Test word next week
  - Haben Sie Zeit für einen Termin der angrenzenden Woche?
- - Test word next week
  - Verleihen Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie Zeit für eine zukünftige Terminwoche?
- - Test word next week
  - Haben Sie Zeit für einen Termin der nächsten Kalenderwoche?
- - Test word next week
  - Nehmen Sie sich die Zeit für einen Termin nächste Woche?
- - Test word next week
  - Haben Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Haben Sie Zeit für einen Termin der nächsten Kalenderwoche?
- - Test word next week
  - Haben Sie Messgerät für einen Termin nächste Woche?
- - Test word next week
  - Besitzen Sie nächste Woche Zeit für einen Termin?
- - Test word next week
  - Hast du nächste Woche Zeit für eine Benennung?
- - Test word next week
  - Haben Sie nächste Woche Zeit für eine Anpassung?
