categories:
- terminauskunft
conversations:
- - Wann habe ich meinen nächsten Termin?
  - $papr003
- - Wann haben Sie meinen nächsten Termin geplant?
  - $papr003
- - Für wann ist mein nächster Termin terminiert?
  - $papr003
- - Für wann ist meine nächste Untersuchung terminiert?
  - $papr003
- - Wann ist meine nächste Untersuchung geplant?
  - $papr003
- - Wann findet meine nächste Untersuchung statt?
  - $papr003
- - Wann ist mein nächster Termin?
  - $papr003
- - Wann habe ich meinen darauffolgenden Termin?
  - $papr003
- - Wann habe ich die nächste Kontrolle?
  - $papr003
- - Wann findet mein nächster Termin bei Ihnen statt?
  - $papr003
- - Welche Uhrzeit findet mein Termin statt?
  - $papr003
- - Wann findet mein Termin statt?
  - $papr003
- - Um welche Uhrzeit findet mein Termin statt?
  - $papr003
- - Wann findet mit meinem Termin statt?
  - $papr003
- - Um welche Uhrzeit findet meine Untersuchung statt?
  - $papr003
- - Wann wird die meine nächste Untersuchung durchgeführt?
  - $papr003
- - Wann findet mein Termin zeitlich statt?
  - $papr003
- - Wann findet mit meinem Termin statt?
  - $papr003
- - Können Sie mir die Uhrzeit meines nächsten Termins sagen?
  - $papr003
- - Um welche Zeit findet der nächste Termin statt?
  - $papr003
- - Kannst du mir sagen, wann mein nächster Termin ist?
  - $papr003
- - Kannst du mir die Zeit meines nächsten Termins sagen?
  - $papr003
- - Können Sie mir Auskunft über die Uhrzeit meines nächsten Termins geben?
  - $papr003
- - Können Sie mir die Uhrzeit des nächsten Termins sagen?
  - $papr003
- - Können Sie mir die Uhrzeit des nächsten Termins bekannt geben?
  - $papr003
- - Kannst du mir rezitieren, wann mein nächster Termin ist?
  - $papr003
- - Wann ist mein nächster Termin zeitlich geplant?
  - $papr003
- - Können Sie mir sagen, wann meine nächste Kontrolle ist?
  - $papr003
- - Können Sie mir sagen, wann meine nächste Kontrolle stattfindet?
  - $papr003
- - Kannst du mir sagen, wann meine nächste Kontrolle ist?
  - $papr003
- - Kannst du mir sagen, wann meine nächste Untersuchung ist?
  - $papr003
- - Kannst du sagst mir, wann mein nächster Termin ist?
  - $papr003
- - Können Sie mir sagen, wann mein zukünftiger Termin ist?
  - $papr003
- - Können Sie mir sagen, wann mein geplanter Termin ist?
  - $papr003
- - Kannst du mir sagen, wann meine nächste Untersuchung ist?
  - $papr003
- - Kannst du mir sagen, wann meine nächste Kontrolle geplant ist?
  - $papr003
- - Kannst du mich erzählen, wenn mein nächster Termin ist?
  - $papr003
- - Kannst du mir sagen, wann meine nächste Untersuchung geplant ist?
  - $papr003